# For now Debian is better that Alpine
# https://pythonspeed.com/articles/alpine-docker-python/
FROM python:3.10.6-slim-buster

ENV PYTHONPATH=/code

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

WORKDIR /code

COPY requirements/requirements-test.txt .
RUN pip3 install -r requirements-test.txt

COPY src ./src
COPY tests ./tests

WORKDIR /code
CMD ["pytest", "tests/users/unit/test_crud_api.py"]